name: "test(master)"

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:
    inputs:
      password:
        required: true
        description: prod upload password
env:
  password: ${{ github.event.inputs.password }}
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Check password
        if: ${{env.password}} == ${{secrets.TEST_PASSWORD}}
        run: |
          echo hihi
