name: "test(master)"

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:
    inputs:
      password:
        required: true
        description: prod upload password
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Check password
        env:
          password: ${{ github.event.inputs.password }}
          secrets_password: ${{secrets.TEST_PASSWORD}}
        if: ${{env.password}} == '1111'
        run: |
          echo hihi
          echo "$secrets_password"
